version: 2

jobs:
    build:
        working_directory: ~/example
        docker:
            - image: lightjason/examples:latest

        branches:
            ignore:
                - master
                - /dev-.*/
                - /jar-.*/

        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"

        steps:
            - checkout
            - run: 
                name: Git Clean
                command: git clean -xdf && git fetch -p && git gc --prune=now
            - run:
                name: Maven Clean
                command: mvn clean dependency:purge-local-repository -DreResolve=false -DactTransitively=true
            - run:
                name: Build
                command: mvn package -Dbuild.number=${CIRCLE_BUILD_NUM} -Dbuild.commit=${CIRCLE_SHA1}

